name: Build Linux and Windows

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Meson and Ninja
      run: sudo apt-get update && sudo apt-get install -y meson ninja-build
    - name: Wrap nlohmann
      run: |
        mkdir -p subprojects
        meson wrap install nlohmann_json
    - name: Setup and Compile Linux
      run: |
        meson setup build_linux -Denable_debug=true
        meson compile -C build_linux
    - name: Package Linux
      run: zip -j linux-hello.zip build_linux/src/hello
    - name: Upload Linux Binary
      uses: actions/upload-artifact@v4
      with:
        name: linux-executable
        path: linux-hello.zip

  build-windows:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install MinGW and Meson
      run: sudo apt-get update && sudo apt-get install -y meson ninja-build mingw-w64
    - name: Create Cross-file
      run: |
        echo "[binaries]" > cross_windows.txt
        echo "c = 'x86_64-w64-mingw32-gcc'" >> cross_windows.txt
        echo "cpp = 'x86_64-w64-mingw32-g++'" >> cross_windows.txt
        echo "ar = 'x86_64-w64-mingw32-ar'" >> cross_windows.txt
        echo "strip = 'x86_64-w64-mingw32-strip'" >> cross_windows.txt
        echo "[host_machine]" >> cross_windows.txt
        echo "system = 'windows'" >> cross_windows.txt
        echo "cpu_family = 'x86_64'" >> cross_windows.txt
        echo "cpu = 'x86_64'" >> cross_windows.txt
        echo "endian = 'little'" >> cross_windows.txt
    - name: Wrap nlohmann
      run: |
        mkdir -p subprojects
        meson wrap install nlohmann_json
    - name: Setup and Compile Windows
      run: |
        meson setup build_win --cross-file cross_windows.txt -Denable_debug=true
        meson compile -C build_win 
    - name: Package Windows
      run: zip -j windows-hello.zip build_win/src/hello.exe
    - name: Upload Windows Exe
      uses: actions/upload-artifact@v4
      with:
        name: windows-executable
        path: windows-hello.zip

  release:
    needs: [build-linux, build-windows]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: linux-executable
        path: .
    - uses: actions/download-artifact@v4
      with:
        name: windows-executable
        path: .
    - name: Release to GitHub
      uses: softprops/action-gh-release@v2
      with:
        files: |
          linux-hello.zip
          windows-hello.zip
